---
title: "Gettign and Cleaning Data Project-Codebook"
author: "Weilun Chiu"
date: "7/21/2020"
output: html_document
---

##Part 1: Variables in the r script
x_train: Training data set
y_train: Activity type for training data set
subject_train: The subject ID of training data set
x_test: Test data set
y_test:Activity type for test data set
subject_test: The subject ID of test data set
features: All the features name
activity_labels: a data frame contains Links between class labels with activity name
Train_Data: Complete training data set, combine x_train, y_train and subject_train
Test_Data:　Complete test data set, combine x_test, y_test and subject_test
Combined_Data: Combined training and test data sets together
Extract_Data: The subset data only includes mean and standard deviation for each measurement.
Summarized_Data: The new data set with the average of each variable for each activity and each subject.

##Part 2: The method to clean and merge data
When combining the training and test data sets in this project, we not only apply function cbind() to combind the Subject ID, Activity ID, and measurement. We also apply functino colnames() to assign the variable names to the data set since the original data download from the URL doesn't have it. Below partial code from script shows the assigning process. 

R-Code
colnames(x_train)<-features[,2]
colnames(y_train)<-"Activity_ID"
colnames(subject_train)<-"Subject_ID"

After the combining and assigning process, we apply function select() to extract the data we need, whcih are mean and standard deviation for each measurement.

R-Code
Extract_Data<-select(Combined_Data, Subject_ID, Activity_ID, contains("mean()"), contains("std()"))

After subsetting from the combined data set, we also use function factor() to replace the numeric variable of column "Activity" in order to let the column present the data in a clear way. 

##Part 3: Summarize the new desired data from the previous tidy data set
In the last part, we apply function group_by() and summarise_if() with pipe line operator to calculate and organize an independent tidy data set with the average of each variable for each activity and each subject.

R-Code
Summarized_Data<-Extract_Data %>% group_by(Subject_ID, Activity_ID) %>% summarise_if(is.numeric, funs(mean))

##Part 4: Export two tidy data sets we accomplish during the cleaning process
We use function write.table to export the tidy data sets we achieve during this process to our work directory as txt file. 

write.table(Extract_Data, "Combined_Tidy_Data.txt", row.names = FALSE)
write.table(Summarized_Data, "Summarized_Tidy_Data.txt", row.names = FALSE)




